name: autoexporter
version: 1.1.15

category: Utility
description: Autoexporter automatically re-exports modules.
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/autoexporter
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Automatically re-export modules.

dependencies:
  base: '>= 4.9.0 && < 4.13'
  Cabal: '>= 1.24.0 && < 1.25 || >= 2.0.1 && < 2.5 || >= 3.0.0 && < 3.1'
  directory: '>= 1.2.6 && < 1.4'
  filepath: '>= 1.4.1 && < 1.5'
ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

executable:
    dependencies:
      autoexporter: -any
    main: Main.hs
    source-dirs: executables
